Milestone 2 components and redux store:PR
kenderb/redux_project_bookstore pull request #2
Opened 2021-02-15 22:10 UTC by kenderb

## Milestone 2: components and redux store
In this branch we:
- Prepared the directory structure.
- Implemented the App component.
- Implemented the BooksList component.
- Implemented the Book component.
- Implemented  the BooksForm component.
- Defined the Redux actions and reducers.
- Initialized  the Redux store.

2021-02-15 23:34 UTC, bellom requested changes
## Hi Team :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 

# Status: Changes Required! ♻️ 

**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2021-02-15 23:34 UTC, bellom commented on src/components/BooksList.js
> +};
Welldone 👍 

Let's update the code.

You need to do the following;
1. Improve the file structure: `BookList` should be placed in `src/containers` directory.
2. `BookList` should connect to Redux store and fetches books from the state using [mapStateToProps](https://react-redux.js.org/using-react-redux/connect-mapstate) [screenshot from pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone2/BooksList/ConnetToRedux.png)

2021-02-15 23:34 UTC, bellom commented on src/components/BooksForm.js
> +const BooksForm = () => (
Improve the file structure: `BooksForm` should be placed in `src/containers` directory.

![image](https://user-images.githubusercontent.com/31897434/90568251-6ba33b80-e1a3-11ea-990d-e73db732b31b.png)
[Microverse Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896827/)

2021-02-16 17:59 UTC, Torres-ssf approved these changes
### Milestone Approved :+1: 
Hi team :hand: 
Awesome job on this milestone.
Good luck with the next one.

Happy coding :computer: 
**Sérgio Torres**

2021-02-16 18:23 UTC, merged

2021-02-16 19:06 UTC, Ceci007 commented
> ### Milestone Approved 👍
> Hi team ✋
> Awesome job on this milestone.
> Good luck with the next one.
> 
> Happy coding 💻
> **Sérgio Torres**

thanks